# Form implementation generated from reading ui file 'C:\Users\Geber.Cruz\OneDrive - Inchcape\Desktop\My Work\Image Processing\rename.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Rename(object):
    def setupUi(self, Rename):
        Rename.setObjectName("Rename")
        Rename.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(parent=Rename)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 20, 601, 327))
        self.tableWidget.setRowCount(10)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(115)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.btnInputDir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnInputDir.setGeometry(QtCore.QRect(20, 396, 30, 30))
        self.btnInputDir.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Geber.Cruz\\OneDrive - Inchcape\\Desktop\\My Work\\Image Processing\\Resources/image.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnInputDir.setIcon(icon)
        self.btnInputDir.setIconSize(QtCore.QSize(30, 30))
        self.btnInputDir.setObjectName("btnInputDir")
        self.btnOutputDir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnOutputDir.setGeometry(QtCore.QRect(20, 430, 30, 30))
        self.btnOutputDir.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\Geber.Cruz\\OneDrive - Inchcape\\Desktop\\My Work\\Image Processing\\Resources/folder.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnOutputDir.setIcon(icon1)
        self.btnOutputDir.setIconSize(QtCore.QSize(30, 30))
        self.btnOutputDir.setObjectName("btnOutputDir")
        self.lblOutputDir = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblOutputDir.setGeometry(QtCore.QRect(60, 430, 351, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblOutputDir.setFont(font)
        self.lblOutputDir.setObjectName("lblOutputDir")
        self.lblInputDir = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblInputDir.setGeometry(QtCore.QRect(60, 396, 351, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblInputDir.setFont(font)
        self.lblInputDir.setObjectName("lblInputDir")
        self.btnAddItem = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAddItem.setGeometry(QtCore.QRect(408, 355, 75, 30))
        self.btnAddItem.setObjectName("btnAddItem")
        self.btnUploadList = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnUploadList.setGeometry(QtCore.QRect(500, 355, 121, 30))
        self.btnUploadList.setObjectName("btnUploadList")
        self.btnCopyRename = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCopyRename.setGeometry(QtCore.QRect(500, 410, 121, 41))
        self.btnCopyRename.setObjectName("btnCopyRename")
        Rename.setCentralWidget(self.centralwidget)

        self.retranslateUi(Rename)
        QtCore.QMetaObject.connectSlotsByName(Rename)

    def retranslateUi(self, Rename):
        _translate = QtCore.QCoreApplication.translate
        Rename.setWindowTitle(_translate("Rename", "File Rename"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Rename", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Rename", "Brand"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Rename", "Image Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Rename", "Image No."))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Rename", "Product ID"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Rename", "Status"))
        self.lblOutputDir.setText(_translate("Rename", "Select an output directory"))
        self.lblInputDir.setText(_translate("Rename", "Select an input directory"))
        self.btnAddItem.setText(_translate("Rename", "Add Item"))
        self.btnUploadList.setText(_translate("Rename", "Load Data from File"))
        self.btnCopyRename.setText(_translate("Rename", "Copy and Rename"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Rename = QtWidgets.QMainWindow()
    ui = Ui_Rename()
    ui.setupUi(Rename)
    Rename.show()
    sys.exit(app.exec())
